- name: Create WordPress environment
  hosts: all
  tasks:
    - name: Build the Docker image
      docker_image:
        name: my-wordpress
        build:
          context: .
    - name: Run the Docker container
      docker_container:
        name: my-wordpress
        image: my-wordpress
        ports:
          - "80:80"
