- name: Deploy WordPress
  hosts: all
  vars:
    wordpress_image: my-wordpress-image
  tasks:
  - name: Pull the WordPress image
    docker_image:
      name: "{{ wordpress_image }}"
      state: present
  - name: Start the WordPress container
    docker_container:
      name: my-wordpress-container
      image: "{{ wordpress_image }}"
      state: started
      ports:
        - "80:80"
      volumes:
        - "/var/www/html/wp-content:/var/www/html/wp-content"
