---
- name: Install WordPress
  hosts: all
  become: true
  vars:
    wp_version: 5.7
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: root
    wp_db_host: localhost
    wp_site_title: My WordPress Site
    wp_admin_user: admin
    wp_admin_password: root
    wp_admin_email: admin@example.com
  tasks:
  - name: Install Apache and PHP
    apt:
      name:
        - apache2
        - php
        - php-mysql
        - libapache2-mod-php
      state: latest

  - name: Enable Apache mod_rewrite
    apache2_module:
      name: rewrite
      state: present

  - name: Create new user for WordPress
  mysql_user:
    name: wordpress
    password: root
    priv: "wordpress.*:ALL"
    host: 192.168.6.10
    login_user: root
    login_password: root

  - name: Download WordPress
    get_url:
      url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
      dest: /tmp/wordpress.tar.gz
      
  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/html/
      remote_src: true

  - name: Create the wp-config.php file
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php
      owner: www-data
      group: www-data
      mode: 0644
     
  - name: Set the correct permissions for the WordPress files
    file:
      path: /var/www/html/wordpress/
      owner: www-data
      group: www-data
      mode: 0755
      recurse: true
      
  - name: Install WordPress
    command: bash -c "cd /var/www/html/wordpress/ && wp core install --url=http://{{ ansible_fqdn }} --title='{{ wp_site_title }}' --admin_user='{{ wp_admin_user }}' --admin_password='{{ wp_admin_password }}' --admin_email='{{ wp_admin_email }}' --skip-email"


