---
- name: Build environment
  hosts: all
  become: true
  tasks:
    - name: Update the package manager
      apt:
        update_cache: true

    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - git
          - python3
          - python3-pip

    - name: Clone the source code repository
      git:
        repo: https://github.com/myuser/myrepo.git
        dest: /opt/myrepo

    - name: Install Python dependencies
      pip:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - Flask
          - requests
          
    - name: Create a virtualenv
      pip:
        name: virtualenv
        state: present
        
    - name: Create a virtual environment
      command: virtualenv /opt/myenv
      
    - name: activate the virtual env
      command: source /opt/myenv/bin/activate
      
    - name:  Run the application
      command: python3 /opt/myrepo/app.py

